Add Pgp signing template
PowerShell/Compliance pull request #15
Opened 2020-11-19 20:12 UTC by TravisEz13

2020-11-19 20:22 UTC, adityapatwardhan requested changes

2020-11-19 20:22 UTC, adityapatwardhan commented on EsrpSign.yml
>      Copy-Item -Path ${{ parameters.buildOutputPath }}\* -Dest ${{ parameters.signOutputPath }}\ -Recurse -Force -Verbose
Should the copy happen before the ESRP task so we can have unsigned files still in buildOutputPath?

2020-11-19 20:22 UTC, adityapatwardhan commented on template-compliance/pgp-sign.yml
> +  - name: "buildOutputPath"
This parameter is not used in this file.

2020-11-19 20:22 UTC, JamesWTruher approved these changes
i think this looks fine

2020-11-19 20:22 UTC, JamesWTruher commented on template-compliance/authenticode-sign.yml
>    condition: and(and(and(succeeded(), eq(variables['Build.Reason'], 'Manual')), ne(variables['SkipSigning'], 'True')), ne(variables['SigningServer'], ''))
this seems to be the same calculation as in EsrpSign. Is there someway to have only a single instance of this calculation be shared between files?

2020-11-19 20:22 UTC, JamesWTruher commented on template-compliance/pgp-sign.yml
> +  condition: and(and(and(succeeded(), eq(variables['Build.Reason'], 'Manual')), ne(variables['SkipSigning'], 'True')), ne(variables['SigningServer'], ''))
yep - and here is that calculation again

2020-11-19 20:43 UTC, TravisEz13 commented on template-compliance/pgp-sign.yml
> +  condition: and(and(and(succeeded(), eq(variables['Build.Reason'], 'Manual')), ne(variables['SkipSigning'], 'True')), ne(variables['SigningServer'], ''))
unfortunately, we tried doing the calculation one time and it causes issues

2020-11-19 20:43 UTC, TravisEz13 commented on template-compliance/pgp-sign.yml
> +    default: "$(Build.ArtifactStagingDirectory)\\build"
```suggestion
```

2020-11-19 20:48 UTC, TravisEz13 commented on template-compliance/authenticode-sign.yml
>    condition: and(and(and(succeeded(), eq(variables['Build.Reason'], 'Manual')), ne(variables['SkipSigning'], 'True')), ne(variables['SigningServer'], ''))
The best I can think of is to pass it in as parameter and it causes issues.  I'll file a feature request for step templates to be conditional.

https://developercommunity.visualstudio.com/idea/1262508/allow-specifying-a-condition-for-a-set-of-template.html

2020-11-19 21:07 UTC, TravisEz13 commented on EsrpSign.yml
>      Copy-Item -Path ${{ parameters.buildOutputPath }}\* -Dest ${{ parameters.signOutputPath }}\ -Recurse -Force -Verbose
This is a behavior change.  I can work on this after I get this work done.

I think this makes sense

2020-11-19 21:08 UTC, TravisEz13 commented on EsrpSign.yml
>      Copy-Item -Path ${{ parameters.buildOutputPath }}\* -Dest ${{ parameters.signOutputPath }}\ -Recurse -Force -Verbose
One thing, is we might end up with unsigned files in the signed folder.

2020-11-20 00:38 UTC, adityapatwardhan approved these changes

2020-11-20 18:05 UTC, merged