Testcustom
PowerShell/Compliance pull request #27
Opened 2021-01-21 17:29 UTC by spaceisfun

2021-01-21 17:56 UTC, TravisEz13 requested changes

2021-01-21 17:56 UTC, TravisEz13 commented on template-compliance/custom-sign.yml
> +      Write-Error "ESRP_TEMPLATE_CUSTOM_JSON variable must be set!"
Add example to readme

2021-01-21 17:56 UTC, TravisEz13 commented on template-compliance/authenticode-sign.yml
> +  - name: "verifySignature"
add examples in readme

2021-01-21 17:56 UTC, TravisEz13 commented on EsrpScan.yml
> +  - name: "scanningService"
add example in readme

2021-01-21 18:41 UTC, spaceisfun commented on EsrpScan.yml
> +  - name: "scanningService"
Added

2021-01-21 18:42 UTC, spaceisfun commented on template-compliance/authenticode-sign.yml
> +  - name: "verifySignature"
Added

2021-01-21 19:02 UTC, TravisEz13 approved these changes

2021-01-21 19:04 UTC, TravisEz13 commented
@JamesWTruher Please review

2021-01-22 01:49 UTC, JamesWTruher reviewed
just a couple of questions

2021-01-22 01:49 UTC, JamesWTruher commented on README.md
> +          **\*.dll
does this pattern need minimatch?

2021-01-22 15:29 UTC, TravisEz13 commented on EsrpSign.yml
> +      Write-Error "Only one of useCustomEsrpJson and certificateId must be set!"
It should be a throw.
```suggestion
      throw "Only one of useCustomEsrpJson and certificateId must be set!"
```

2021-01-22 15:29 UTC, TravisEz13 commented on README.md
> +          **\*.dll
it does

2021-01-22 18:55 UTC, spaceisfun commented on README.md
> +          **\*.dll
good catch, fixed

2021-01-22 22:14 UTC, merged